# Generated by Django 3.1.12 on 2025-05-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('cuisine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('spiciness_level', models.IntegerField(blank=True, null=True)),
                ('suitable_for_diet', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
